### ISSUE TITLE
Comparison with Redux-ORM?

### ISSUE THREAD

**Issue by markerikson** [SevenOutman/redux-eloquent#1]
This bears a resemblance with https://github.com/tommikaikkonen/redux-orm .  I'd be curious to hear your thoughts on similarities and differences between the libraries.

**Comment by SevenOutman** [comment]
@markerikson First of all thank you for your attention.

Basically none. 

This package has nothing to do with the idea or source of `redux-orm`. I got the idea and motivation to make this package from my business project, just to make me and my team coding easier. It's implementation is inspired by [this article on _Hackernoon_](https://hackernoon.com/shape-your-redux-store-like-your-database-98faa4754fd5).

If you go really strict, there are 2 points of relationship between this package and `redux-orm`: 
- 1. When naming this package,  I went check whether a "redux-orm" existed. (And it finally got its name from [Laravel's `Eloquent`](https://laravel.com/docs/5.5/eloquent)).
- 2. I went though usage example sections in several "frontend ORM" repos, including `redux-orm`, to help me design better APIs that are simpler to understand and use.

If you want to know more detailed, feel free to reopen, or just [email me](mailto:leishenghao@126.com).

**Comment by markerikson** [comment]
To clarify: I wasn't asking if `redux-eloquent` was directly inspired by `redux-orm`.  I was asking for a comparison of features, API, use cases, and usage.

For example, both libraries appear to let you define model types and fields within those models, then fetch a list of those model types from a Redux state.

**Comment by SevenOutman** [comment]
@markerikson I misunderstood.

I think redux-eloquent is packed with apis designed to be easier to use and understand while redux-orm can be more extendable and customizable.

Here's a brief comparison based on my own understanding of redux-orm.

redux-eloquent allows you define models in simpler syntax. While redux-orm defines Book attrs with `id: attr(), publisher: fk('Publisher'), authors:many('Author')`, redux-eloquent prefer `id: Number, publisher: Publisher, authors: [Author]`.

redux-orm provides you apis to create reducer and selectors on your own, while redux-eloquent handles them for you and expose simpler apis only for most frequent uses. If you are a developer using some backend languages and frameworks, this feels like redux-orm provides you db operation apis but redux-eloquent only provides ORMs.

redux-eloquent handles nested data well. As not mentioned (yet) in README, save() methed handles nested data with normalizr, which means you can save(aBookWithAnAutherObject), while redux-orm prefer terms like book.authors.add(). I find this term cool as well but came to drop it the last minute. (Because our backend api returns nested data)

Hope this helps.
